### ISSUE TITLE
Could not find file 'C:\src\mfcmapi\mapistub\mapistub.vcxproj

### ISSUE THREAD

**Issue by stringarray** [microsoft/mfcmapi#559]
On a clean github clone, the .sln and MFCMapi projects are found, but when opening them with Visual Studio, (2019 and 2022) The message C:\src\mfcmapi\mapistub\mapistub.vcxproj : error  : The project file could not be loaded. Could not find file 'C:\src\mfcmapi\mapistub\mapistub.vcxproj'.  C:\src\mfcmapi\mapistub\mapistub.vcxproj
is displayed and building is impossible.

**Comment by tapiov** [comment]
Just for anyone stumbling here. 

Clone repository https://github.com/microsoft/MAPIStubLibrary
Rename MAPIStubLibrary => mapistub
Copy mapistub under mfcmapi

My build succeed this way.

**Comment by stephenegriffin** [comment]
Clone like this:
`git clone --recursive https://github.com/microsoft/mfcmapi.git`
That'll pull the submodule for you.

**Comment by stephenegriffin** [comment]
Updated docs #703
