### ISSUE TITLE
Unable to unzip - MFCMAPI.x64.exe.23.0.23089.01.zip

### ISSUE THREAD

**Issue by smithkj12** [microsoft/mfcmapi#643]
downloaded - MFCMAPI.x64.exe.23.0.23089.01.zip

Tried to Unzip to extract MFCMapi.exe and having issues unzipping the file, when opening WINZIP app and selecting unzip to here... - get Central and local directory mismatch for file "MFCMapi.exe" (compressed size - local: 2046629 central: 2108354)

full notes:
Extracting file: C:\Temp\MFCMAPI.x64.exe.23.0.23089.01.zip
Extracting to "C:\Temp\"
Use Path: yes   Overlay Files: no
Extracting MFCMapi.exe
Central and local directory mismatch for file "MFCMapi.exe" (compressed size - local: 2046629  central: 2108354).
Severe Error: Local and central compressed size values don't match.

please advise how I can obtain a copy of MFCMapi.exe to use with Outlook 2016 on 64 Bit laptop.

**Comment by stephenegriffin** [comment]
I don't reproduce this problem. Windows has a built in ZIP handler - can it extract it if winzip isn't working?

**Comment by smithkj12** [comment]
I ended up copying the ZIP file to a USB stick then onto another device without WinZip installed, and was able to open with Windows ZIP handler.  Thank you for the resolution to opening the ZIP file.
