### ISSUE TITLE
intention of registry::useGetPropList ?

### ISSUE THREAD

**Issue by timepp** [microsoft/mfcmapi#761]
Hi,

I have a large property bag and I MFCMAPI will fail with MAPI_E_OUT_OF_MEMORY when it's trying to get all properties:

```C++
	_Check_return_ HRESULT GetPropsNULL(
		_In_ LPMAPIPROP lpMAPIProp,
		ULONG ulFlags,
		_Out_ ULONG* lpcValues,
		_Deref_out_opt_ LPSPropValue* lppPropArray)
	{
		auto hRes = S_OK;
		*lpcValues = NULL;
		*lppPropArray = nullptr;

		if (!lpMAPIProp) return MAPI_E_INVALID_PARAMETER;
		LPSPropTagArray lpTags = nullptr;
		if (registry::useGetPropList)
		{
			output::DebugPrint(output::dbgLevel::Generic, L"GetPropsNULL: Calling GetPropList\n");
			hRes = WC_MAPI(lpMAPIProp->GetPropList(ulFlags, &lpTags));

			if (hRes == MAPI_E_BAD_CHARWIDTH)
			{
				EC_MAPI_S(lpMAPIProp->GetPropList(NULL, &lpTags));
			}
			else
			{
				CHECKHRESMSG(hRes, IDS_NOPROPLIST);
			}
		}
		else
		{
			output::DebugPrint(output::dbgLevel::Generic, L"GetPropsNULL: Calling GetProps(NULL) on %p\n", lpMAPIProp);
		}

		hRes = WC_H_GETPROPS(lpMAPIProp->GetProps(lpTags, ulFlags, lpcValues, lppPropArray)); **<-- error **here**
		MAPIFreeBuffer(lpTags);

		return hRes;
	}
```

But if I change to not passing prop list to the call of `MAPIProp::GetProps` then the call will succeed and I can see all the properties in the UI successfully.

I found this behavior is controlled by `registry::useGetPropList`. And corresponding UI below:
![image](https://github.com/user-attachments/assets/a54057dc-ad6e-4063-ac46-6f7d18f99ffa)

What's the intention of this setting? is that safe to disable it?

**Comment by stephenegriffin** [comment]
It's just two different ways of accomplishing basically the same thing. I left both ways in because, as you've now seen, sometimes one way works when the other fails.
