### ISSUE TITLE
Incorrect code signing certificate used for release - MFCMAPI 24.0.24358.03

### ISSUE THREAD

**Issue by amaiman** [microsoft/mfcmapi#800]
The MFCMAPI 24.0.24358.03 release's executables appear to be code signed with the untrusted "TestAzureEngBuildCodeSign" code signing certificate as opposed to the standard trusted "Microsoft Corporation" certificate.

**Comment by stephenegriffin** [comment]
I see what happened - pulling release and will reissue shortly

**Comment by stephenegriffin** [comment]
should be fixed now
